---
title: "Dates"
author: "Gregory J. Matthews"
date: "11/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Dates
```{r}
#https://docs.python.org/3/library/datetime.html#strftime-and-strptime-behavior

#Bulit in R functions
Sys.Date()
Sys.time()
date()
```  
#Adding and subtracting dates
```{r}
dates <- c("1982-07-25","2023-04-04")
class(dates)
#Converts character to a date
dates <- as.Date(dates)
class(dates)
#My age in days
dates[2] - dates[1]
#My age in years (Not quite exact, right?  But really close)
(dates[2] - dates[1])/365
```

#Formatting dates
```{r}
#%d - dat as a number 
#%a - abbreviated month
#%A - unabbreviated month
#%m - month numeric
#%b - abbreviated month
#%B - unabbreviated month
#%y - 2 digit year
#%Y - 4 digit year
```


```{r}
#Some examples
format(dates[1], format = "%B %d %y")
format(dates[1], format = "%b %d %Y")
format(dates[1], format = "%m-%d-%y")


dates <- c("1982-07-25","2022-11-07")
#Converts character to a date
#default format is yyyy-mm-dd
as.Date(dates)

dates <- c("7/25/82","7/25/82")
#This doesn't work!
#as.Date(dates)
#Must specify the format
as.Date(dates, "%m/%d/%y")
#Once you do that, you can change the format
format(as.Date(dates, "%m/%d/%y"), format = "%B-%d-%Y")

```
#Dates as integers
```{r}
as.Date(32768, origin = "1900-01-01")
#Different origins
as.Date(32768, origin = "1970-01-01")
```

```{r}
library(lubridate)
#Note libridate is part of the tidyverse
#functions such as ymd, ymd_hms, dmy_hms, mdy, etc.
ymd(20101215)
class(ymd(20101215))

mdy("4/1/17")

#Pull out different components of the data
bday <- dmy("25/07/1982")
month(bday)
wday(bday, label = TRUE)


year(bday) <- 2016
bday
wday(bday, label = TRUE)
```
#Date and time
```{r}
time <- ymd_hms("2010-12-13 15:30:30")
time
hour(time)
minute(time)
second(time)

# Changes printing
with_tz(time, "America/Chicago")

# Changes time
force_tz(time, "America/Chicago")

```
```{r}
library(nycflights13)
ins <- read.csv("/Users/gregorymatthews/Dropbox/Public/inspections_clean.csv")
```

# In class questions
 - What day of the week do the most inspections occur. 
 - What is the pass rate (i.e. results == "Pass") of each month for all inspections and which month had the lowest pass rate.  


```{r}
library(tidyverse)
ins$inspection_date <- as.Date(ins$inspection_date)

sub<- ins %>% mutate(dow = wday(inspection_date, label = TRUE)) %>% group_by(dow, inspection_type) %>% summarize(count = n()) 

g <- ggplot(aes(x = dow, y = count, fill = inspection_type), data = sub) + geom_bar(stat = "identity")

ggplotly(g)

```

```{r}
ins <- read.csv("/Users/gregorymatthews/Dropbox/Public/inspections_clean.csv")
library(tidyverse)
library(lubridate)
#Pass rate by month
ins %>% mutate(inspection_date = as.Date(inspection_date), 
                      month = month(inspection_date, label = TRUE)) %>% group_by(month) %>% summarize(pass_rate = mean(results == "Pass")) %>% arrange(pass_rate)


#Number of inspections by month day
#Pass rate by month
ins %>% mutate(date = as.Date(inspection_date), 
                      dayofmonth = mday(date)) %>% group_by(dayofmonth) %>% summarize(num_ins = n()) %>% arrange(num_ins)




#Average number of tests by day of month
sub <- ins %>% mutate(date = as.Date(inspection_date), 
               month = month(date),
              dayofmonth = mday(date)) %>% group_by(month,dayofmonth) %>% summarize(num_ins = n()) %>% group_by(dayofmonth) %>% summarize(mn_ins = mean(num_ins), count = n()) %>% arrange(-mn_ins)

ggplot(aes(x = dayofmonth, y = mn_ins), data = sub) + geom_point() + geom_line()



```

```{r}
#https://www.dropbox.com/s/b479vozvacya739/fitBitData20160630.RData?dl=0
load("/Users/gregorymatthews/Dropbox/Rart/DataArtProject/fitBitData20160630.RData")

steps[1,]
sleep[1,]
hr[1,]
load("/Users/gregorymatthews/Dropbox/Rart/DataArtProject/fitBitData20160630.RData")
sub <- hr %>% mutate(dateTime2 = as.POSIXct(hr$dateTime,format = "%Y-%m-%d %H:%M:%OS"), month = month(dateTime2), hour = hour(dateTime2) + minute(dateTime2)/60 + second(dateTime2)/3600) %>% group_by(hour, month) %>% summarize(mn = mean(`heart-rate`, na.rm = TRUE))

ggplot(aes(x = hour, y = mn, colour = factor(month)), data = sub ) + geom_line() + geom_point() +geom_smooth()
```
 
 
 